/**
 * The visual constants of the automata design programme.
 *
 * The programme is minimalistic and typographic: one monospace family, a black
 * void, a single accent, hairline rules, and ornament generated by an
 * elementary cellular automaton. Every screen and overlay draws its values from
 * here — no screen defines a colour, a size, or a spacing of its own.
 *
 * The tokens are emitted as CSS custom properties by
 * {@link buildDesignStyleSheet}, so the CSS and the TypeScript never drift.
 */
export const DESIGN_TOKENS = {
  /** Surface and ink colours. */
  COLOR: {
    /** Page ground; also the dead-cell colour of the simulation grid. */
    VOID: '#000000',
    /** Ground of an overlay bar that sits on top of the running simulation. */
    PANEL: 'rgba(0, 0, 0, 0.72)',
    /** Ground of a full-page overlay that must leave the grid dimly visible. */
    VEIL: 'rgba(0, 0, 0, 0.82)',
    /** Primary text. */
    INK: '#e8e8e8',
    /** Secondary text: headings, labels, readouts. */
    INK_DIM: '#8c8c8c',
    /** Tertiary text: ornament and disabled controls. */
    INK_FAINT: '#454545',
    /** Hairline borders. */
    RULE: '#2e2e2e',
    /** The single accent: the human player's red, brightened for legibility on the void. */
    ACCENT: '#ff4136',
  },

  /** Typography. The character cell is the unit of the whole layout. */
  FONT: {
    FAMILY: "'DejaVu Sans Mono', 'Cascadia Mono', 'Courier New', monospace",
    /** Title size, used once per screen. */
    SIZE_CANON: '2.5rem',
    /** Section-heading size. */
    SIZE_HEADING: '1.125rem',
    /** Body size. */
    SIZE_BODY: '0.9rem',
    /** Overlay, label, and ornament size. */
    SIZE_MICRO: '0.75rem',
    /** Letter spacing applied to every uppercase run. */
    TRACKING: '0.18em',
    LINE_HEIGHT: '1.5',
  },

  /** Spacing scale. Every gap and pad is one of these four steps. */
  SPACE: {
    HAIR: '0.25rem',
    TIGHT: '0.5rem',
    STEP: '1rem',
    WIDE: '2rem',
  },

  /** Fixed measures, expressed in character cells wherever the grid allows. */
  MEASURE: {
    /** Width the speed readout is held at, so the control bar does not reflow. */
    READOUT: '14ch',
    /** Edge length of a player colour swatch. */
    SWATCH: '0.75rem',
  },

  /** Width of every border in the programme; there is only one. */
  BORDER_WIDTH: '1px',

  /** Parameters of the elementary automaton that generates the ASCII ornament. */
  ORNAMENT: {
    /** Wolfram rule number of the ornament automaton (Rule 90 — the Sierpinski rule). */
    RULE_NUMBER: 90,
    /** Generations evolved before the ornament row is taken. */
    GENERATIONS: 16,
    /** Character width of an ornament row. */
    COLUMNS: 47,
  },
} as const;
